### ISSUE TITLE
Could I use clonal information from HATCHet to MACHINA?

### ISSUE THREAD

**Issue by biosurgeon** [raphael-group/machina#12]
Hi, 

Thanks for the nice software!

I got clonal information from HATCHet (Holistic Allele-specific Tumor Copy-number Heterogeneity), and I want to infer clonal seeding via MACHINA algorithm.

HATCHet output provides clonal information with estimated proportion of the clone for each sample and bin, and the coverages of A and B allele. 
I may calculate confidence of interval of each clone for each sample with beta distribution, but to be honest, I don't know how to do with those data from HATCHet..
Below is an example of outcome from HATCHet. (two sample 3 clones)

Could you help me?

```
#CHR    START   END     SAMPLE  RD      #SNPS   COV     ALPHA   BETA    BAF     CLUSTER cn_normal       u_normal        cn_clone1
       u_clone1        cn_clone2       u_clone2        cn_clone3       u_clone3
chr1    250000  500000  WESDemo1        1.15713 1       26      11      15      0.423077        5       1|1     0.071242        2|1     0       2|2     0.10161 1|1     0.827148
chr1    250000  500000  WESDemo2        1.1233  1       32      12      20      0.375   5       1|1     0.245793        2|1     0.682487        2|2     0.07172 1|1     0
chr1    1000000 1250000 WESDemo1        1.08678 2       106     86      126     0.40566 15      1|1     0.071242        1|1     0
       1|1     0.10161 1|1     0.827148
chr1    1000000 1250000 WESDemo2        0.955499        2       85      77      94      0.450292        15      1|1     0.245793
        1|1     0.682487        1|1     0.07172 1|1     0
```

**Comment by gsatas** [comment]
Hi! Thank you for your question. Unfortunately, MACHINA's `pmh_ti` mode which simultaneously infers a phylogeny and reconstructs a seeding history is designed specifically for SNV data. As a result, MACHINA cannot directly take HATCHET results as input.

However, one could run MACHINA in `phm_tr` mode which takes as input a phylogeny and infers a seeding history while resolving polytomies in the input phylogeny. In order to do this, one must first infer a phylogeny using the HATCHET copy-number clones. This can be done with our Copy-Number Tree algorithm (https://github.com/raphael-group/CNT-ILP). The resulting phylogeny can then be used as input for MACHINA as described in the `pmh_tr` section of the documentation.

Please let us know if you have further questions!
